### ISSUE TITLE
dx.from_tables fails when hyphen exists in catalog or schema name

### ISSUE THREAD

**Issue by siddarthrokkam** [databrickslabs/discoverx#92]
Throws the following error

Invalid from_tables statement '{from_tables}'. Should be a string in format 'table_catalog.table_schema.table_name'. You can use '*' as wildcard."

**Comment by siddarthrokkam** [comment]
@edurdevic @david-tempelmann @nfx This could be the fix

in explorer.py update regex as follow 
FROM_COMPONENTS_EXPR = r"^(([0-9a-zA-Z_\*-]+)\.([0-9a-zA-Z_\*-]+)\.([0-9a-zA-Z_\*-]+))$"

**Comment by souravg-db** [comment]
This issue is fixed with https://github.com/databrickslabs/discoverx/pull/94

**Comment by souravg-db** [comment]
Fixed in [v0.0.8](https://github.com/databrickslabs/discoverx/releases/tag/v0.0.8)

**Comment by mohammedkhu** [comment]
@souravg-db just tested this, still facing the same issue, tried as follows
1. `` from_tables = "data-eng-prod-zenni-bronze.*.*" ``
2. `` from_tables = "`data-eng-prod-zenni-bronze`.*.*" ``
